### ISSUE TITLE
Session Files Getting Created Even After Using This Library

### ISSUE THREAD

**Issue by MirazMac** [Snawoot/php-storageless-sessions#1]
Here is my code, placed at the top of my init file.
```php
require 'vendor/autoload.php';
ob_start('ob_gzhandler');
$secret = "XXXXXXXXXXXXXXXXXXX";
$handler = new VladislavYarmak\StoragelessSession\CryptoCookieSessionHandler($secret);
session_set_save_handler($handler, true);
session_start();
```
This works perfectly, the cookies are being sent and writing, reading the session data is working fine. But the problem is even after I'm using this custom session handler, the session files are still being created at **/tmp** ( as defined in php.ini ) .
Note:
 I checked my **php.ini** and verified that **session.auto_start** is disabled. Also this code is placed at the very first beginning of my app, there is no chance that the sessions are getting by started before executing this code.
Sorry for my bad English.

**Comment by Snawoot** [comment]
Hello @mirazmac,

I've checked it on my box with PHP 7.0 and can't reproduce this issue. Probably you have multiple domains or webapplications on your server and some of them are using classic `files` handler for sessions. Please check contents of such session files for any clues about application created them.
